version: '3.8'

services:
  db:
    image: mysql:8.3.0
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: my_root_password
      MYSQL_DATABASE: movapp
    volumes:
      - ./db:/docker-entrypoint-initdb.d
