version: '3.8'

services:
  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: r00t_p4ssw0rd
      MYSQL_DATABASE: movapp
    volumes:
      - mysql:/var/lib/mysql
    
volumes:
  mysql: