export const GENRES = {
    action:'Acción',
    Adventure:'Aventura',
    Animation : 'Animación',
    Comedy : 'Comedia',
    Crime : 'Crimen',
    Documentary : 'Documental',
    Drama : 'Drama',
    Family : 'Familia',
    Fantasy : 'Fantasía',
    History : 'Historia',
    Horror : 'Terror',
    Music : 'Música',
    Mystery : 'Misterio',
    Romance : 'Romance',
    ScienceFiction : 'Ciencia ficción',
    TVMovie : 'Película de televisión',
    Thriller : 'Thriller',
    War : 'Guerra',
    Western : 'Western',
}